version: '3.8'

services:
  cand_man_api:
    build:
      context: ./cand_man_api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cand_man_api:/app
    ports:
      - "8000:8000"
