version: '3.8'

services:
  cand_man_api:
    build:
      context: ./cand_man_api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cand_man_api:/app
    ports:
      - "8000:8000"

  cand_man_ui:
    build:
      context: ./cand_man_ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - cand_man_api
